### ISSUE TITLE
Error running suave

### ISSUE THREAD

**Issue by kk86bioinfo** [tobiasrausch/delly#38]
```
127.0.0.1 - - [16/Mar/2016 12:32:44] "GET /depth/L1T/L1/1?n=10000 HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2016 12:32:48] "GET /calls/1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/delly/vis/suave/suave_server.py", line 56, in calls
    chrom2 = chr2_re.search(row[7]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by meiers** [comment]
Hi kk86bioinfo,
did you supply a Delly VCF file? It looks like it did not contain the "CHR2" field in the info column.
I will upload a version with better error handling
